"""document embedding_status enum

Revision ID: 8bde1b4b8e1b
Revises: 3b1bc9eab499
Create Date: 2025-12-30 14:51:41.713567

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bde1b4b8e1b"
down_revision: Union[str, None] = "3b1bc9eab499"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum_type = sa.Enum(
        "pending",
        "processing",
        "completed",
        "failed",
        name="document_embedding_status",
    )
    enum_type.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "documents",
        "embedding_status",
        existing_type=sa.VARCHAR(length=50),
        type_=enum_type,
        postgresql_using="embedding_status::document_embedding_status",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum_type = sa.Enum(
        "pending",
        "processing",
        "completed",
        "failed",
        name="document_embedding_status",
    )

    op.alter_column(
        "documents",
        "embedding_status",
        existing_type=enum_type,
        type_=sa.VARCHAR(length=50),
        postgresql_using="embedding_status::text",
        existing_nullable=False,
    )

    enum_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
